"""add ip address tracking

Revision ID: a5ecd8178e02
Revises: 6ba6ab629fbf
Create Date: 2022-01-29 08:08:05.730089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ecd8178e02'
down_revision = '6ba6ab629fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('ip', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_site_ip'), 'site', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_ip'), table_name='site')
    op.drop_column('site', 'ip')
    # ### end Alembic commands ###
