"""added added column to Site to see when new sites are added

Revision ID: bb3296841762
Revises: a5ecd8178e02
Create Date: 2022-01-29 08:20:10.153609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3296841762'
down_revision = 'a5ecd8178e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'added')
    # ### end Alembic commands ###
